### ISSUE TITLE
HAR collected from Chrome gives wrong start values?

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#102]
Run using <code>--experimental.nativeHar</code> and use Chrome.

When we parse the performance log, it seems that most responses starts at the same time (even though we do HTTP/1):
<img width="852" alt="screen shot 2016-01-23 at 19 26 27" src="https://cloud.githubusercontent.com/assets/540757/12534756/5cd0197c-c266-11e5-933d-bbc13d1aa839.png">

But if we check the dev tools generated har (SAVE AS HAR) it looks like this:
<img width="858" alt="screen shot 2016-01-23 at 19 25 58" src="https://cloud.githubusercontent.com/assets/540757/12534760/7a76bb7a-c266-11e5-8480-e87cd1c01471.png">

**Comment by beenanner** [comment]
@soulgalore @tobli it doesn't look like the HAR generated by browsertime has the connection id field. That could help in validating this issue and could be useful for other types of analysis.

https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/HAR/Overview.html#sec-object-types-entries
> connection [string, optional] (new in 1.2) - Unique ID of the parent TCP/IP connection, can be the client port number. Note that a port number doesn't have to be unique identifier in cases where the port is shared for more connections. If the port isn't available for the application, any other unique connection ID can be used instead (e.g. connection index). Leave out this field if the application doesn't support this info.

https://developer.chrome.com/devtools/docs/protocol/1.1/network#response:-object

![image](https://cloud.githubusercontent.com/assets/723985/12700350/5093afac-c7ac-11e5-89bf-69b29ddd5d92.png)

I'll open up a pull-request with that added feature maybe it will give some insight into what's happening with this issue.

**Comment by beenanner** [comment]
Opened #104 to surface the connection ids in chrome.

**Comment by tobli** [comment]
Merged #104 now, but we'll have to iterate on the perflog parsing. Not sure if it's issues with the data, our calculations or our interpretations if their meaning. The Chrome docs aren't super clear to me.

**Comment by beenanner** [comment]
@tobli @soulgalore quick update as I had some time tonight to take a look at this issue. If the connection setup times on a fresh connection(queuing, stalling, dns lookup, etc) are not taken in account that could explain the reason for the request to all appear to start at the same time.

![image](https://cloud.githubusercontent.com/assets/723985/12740418/f1da040c-c940-11e5-919b-e755b33221b1.png)

I did confirm that multiple requests are showing as starting at the same time and have the same connection ids which shouldn't happen, so something is amiss with the parser. I'll dig into it a bit more tomorrow when I have a little more time.

**Comment by beenanner** [comment]
Still no luck on tracking down this issue. I've been using @tobli debug chrome har branch with the additional options set to output the raw values of the events. I've then compared that file to the generated har from bt and so far the values all seems to line up with each other. :-( I'll run a few more test tomorrow as time allows and dig into chrome documentation to see if I can find anything there.

**Comment by tobli** [comment]
Thanks @beenanner! I haven't had the time to look into chrome hars in a while, so any digging is appreciated.

**Comment by soulgalore** [comment]
maybe we should ask someone in the chrome team, see if they could point us in the right direction if we don't find anything in the docs?

**Comment by beenanner** [comment]
I've attempted to correct this issue by looking at previous connection id times and off setting the start time of the newer connections. Pull-request #108 open.

**Comment by beenanner** [comment]
I opened #117 to also help in correcting this issue.

**Comment by soulgalore** [comment]
This works now right so we can close the issue?

**Comment by soulgalore** [comment]
yep closing.
