### ISSUE TITLE
Slow first load

### ISSUE THREAD

**Issue by rmarx** [tobli/browsertime#105]
Hello there,

I am seeing a consistent very slow load for every first page load (over 2 times as long as any subsequent request), in phantomjs, firefox and chrome, across every website I test.  I am also seeing this in sitespeed.io (which led me here in the first place).

At first I thought it was because of caching (cache not cleared in between each request?) but (for chrome) I have verified that you restart the browser with a new empty user profile for every run, so that shouldn't be it. 

I'm not sure if this is "normal" behaviour (ex. first run always takes longer because of selenium/proxy setup time) or if this shouldn't happen at all. I am running this in a Ubuntu VM that is somewhat resource constrained, so that might also be the problem, but that still doesn't really explain the big difference between the first and subsequents imo.

Is this something you have encountered before / any idea what the problem might be?

Some logs:
<pre>
rmarx@ubuntu:~$ node node_modules/browsertime/bin/browsertime.js -u http://www.google.be -v -n 5
Starting proxy on port 2001, will wait at most 15000 ms
Fetching http://www.google.be (1 of 5)
loading url took <b>17028</b> milliseconds
Fetching http://www.google.be (2 of 5)
loading url took 5517 milliseconds
Fetching http://www.google.be (3 of 5)
loading url took 3147 milliseconds
Fetching http://www.google.be (4 of 5)
loading url took 2858 milliseconds
Fetching http://www.google.be (5 of 5)
loading url took 5308 milliseconds

rmarx@ubuntu:~$ node node_modules/browsertime/bin/browsertime.js -u http://www.google.be -v -n 5 -b phantomjs
Starting proxy on port 2001, will wait at most 15000 ms
Fetching http://www.google.be (1 of 5)
loading url took <b>1807</b> milliseconds
Fetching http://www.google.be (2 of 5)
loading url took 484 milliseconds
Fetching http://www.google.be (3 of 5)
loading url took 436 milliseconds
Fetching http://www.google.be (4 of 5)
loading url took 474 milliseconds
Fetching http://www.google.be (5 of 5)
loading url took 417 milliseconds

rmarx@ubuntu:~$ node node_modules/browsertime/bin/browsertime.js -u http://www.tweakers.net -v -n 10 -b phantomjs
Starting proxy on port 2001, will wait at most 15000 ms
Fetching http://www.tweakers.net (1 of 10)
loading url took <b>4069</b> milliseconds
Fetching http://www.tweakers.net (2 of 10)
loading url took 1343 milliseconds
Fetching http://www.tweakers.net (3 of 10)
loading url took 1503 milliseconds
Fetching http://www.tweakers.net (4 of 10)
loading url took 1319 milliseconds
Fetching http://www.tweakers.net (5 of 10)
loading url took 1768 milliseconds
Fetching http://www.tweakers.net (6 of 10)
loading url took 1205 milliseconds
Fetching http://www.tweakers.net (7 of 10)
loading url took 1484 milliseconds
Fetching http://www.tweakers.net (8 of 10)
loading url took 1239 milliseconds
Fetching http://www.tweakers.net (9 of 10)
loading url took 2125 milliseconds
Fetching http://www.tweakers.net (10 of 10)
loading url took 1319 milliseconds

rmarx@ubuntu:~$ node node_modules/browsertime/bin/browsertime.js -u http://www.tweakers.net -v -n 10 -b firefox
Starting proxy on port 2001, will wait at most 15000 ms
Fetching http://www.tweakers.net (1 of 10)
loading url took <b>32022</b> milliseconds
Fetching http://www.tweakers.net (2 of 10)
loading url took 9499 milliseconds
Fetching http://www.tweakers.net (3 of 10)
loading url took 13060 milliseconds
Fetching http://www.tweakers.net (4 of 10)
loading url took 9273 milliseconds
Fetching http://www.tweakers.net (5 of 10)
loading url took 14271 milliseconds
Fetching http://www.tweakers.net (6 of 10)
loading url took 11762 milliseconds
Fetching http://www.tweakers.net (7 of 10)
loading url took 11452 milliseconds
Fetching http://www.tweakers.net (8 of 10)
loading url took 9458 milliseconds
Fetching http://www.tweakers.net (9 of 10)
loading url took 12199 milliseconds
Fetching http://www.tweakers.net (10 of 10)
loading url took 10673 milliseconds
</pre>

Ubuntu 14.04 64bit
Browsertime 0.12.2
PhantomJS 2.1.1
Chrome 46.0.2490.71

**Comment by tobli** [comment]
Hi!
We try our best to clear all browser caches between runs, but getting consistent numbers is hard. Running www.tweakers.net locally I see the same behavior, but not as extreme. Comparing the different runs from the har file gives a hint of what's going on. The first run has lot's of time spent on dns lookups, whereas following runs have hardly no dns time at all. Since dns caching happens both on the OS level, and in the external infrastructure (i.e. your nearest dns server) it's not possible to really get rid of this effect.

What I recommend is to run a few runs and check the stats from the output. Wether you want to look at the first run (worst case) or a median over many runs depends on your use case.

Hope this helps!
/Tobias
