### ISSUE TITLE
Add screenshot  functionality

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#124]
It "should" be easy to add screenshot capability using selenium. Would be good also so that the coach could have that functionality so you are sure what you test.

**Comment by tobli** [comment]
Pass --screenshot to save screenshots of each run.

**Comment by parangsjo** [comment]
Hey,

Have you seen that latest movie? I don't know what all the fuss is about. Before you watch it read a review here <http://tholtycuvo.politicalresumes.us/xynmth>

Yours sincerely, pa@rangsjo.com
