### ISSUE TITLE
Add support for Basic Auth

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#24]
I often get issues of adding Basic Auth for sitespeed.io, so I will probably look into it the coming month ...

**Comment by tobli** [comment]
Long overdue ping!
Basic auth support is in place, use like this: 
browsertime -u http://httpbin.org/basic-auth/user/passwd --basicAuth user:passwd

**Comment by soulgalore** [comment]
Hey @jpvincent in the older 0.9.x version we used a proxy in front that added that basic auth, now we don't use a proxy. Right now only way is to add the name/pw in front of the URL but it would of course be nice to not need that. I've haven't checkd in a while if Selenium supports that now? Could you please a create new issue for us, that would be easier just to keep track on.

Thanks!
Peter
