### ISSUE TITLE
Handle port already in use for BMP

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#68]
When I test the new version using sitespeed, and I already got something on the same port, I get ouput like this:
<pre>
$ bin/sitespeed.js -u http://www.sitespeed.io -b chrome -n 1 -d 0
info: OS: darwin 14.0.0 sitespeed:3.0.0-beta-4  phantomJs:1.9.8 java:java version "1.7.0_71"
info: Will crawl from start point http://www.sitespeed.io with crawl depth 0
info: Will analyze 1 pages
info: Starting proxy on port 9092, will wait at most 3000 ms
error:
</pre> and then it hangs. Maybe the fix is in sitespeed though :)

The browsermob log looks like this:
<pre>
{"level":"error","message":"stderr:java.net.BindException: Address already in use\n","timestamp":"2014-12-01T13:07:53.842Z"}
{"level":"error","message":"stderr:\tat sun.nio.ch.Net.bind0(Native Method)\n\tat sun.nio.ch.Net.bind(Net.java:444)\n\tat sun.nio.ch.Net.bind(Net.java:436)\n\tat sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)\n\tat sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)\n\tat org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:162)\n\tat org.eclipse.jetty.server.AbstractConnector.doStart(Abst:{"level":"error","message":"stderr:INFO 12/01 13:07:52 n.s.u.i.d.DataBuild~ - No pattern available for 'Other'.\n","timestamp":"2014-12-01T13:07:52.438Z"}
</pre>

Best
Peter

**Comment by tobli** [comment]
Since 0.8.22 this should be resolved (Browsertime will look for a free port to start the proxy.
