### ISSUE TITLE
Stats collide

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#81]
There's no way today to separate timing statistics and userDefined stats. Today it looks like this (running a script called *scripts*:
<pre>
"statistics":[{"name":"backEndTime","min":"302","max":"707","p10":"302","p70":"707","p80":"707","p90":"707","p99":"707","median":"499","mean":"503"},
{"name":"scripts","min":"18","max":"18","p10":"18","p70":"18","p80":"18","p90":"18","p99":"18","median":"18","mean":"18"}]
</pre>

We need to discuss how we wanna do it in the future, separating timings with other values. I can think of these different solutions:
* Do nothing 
* Let each script return type and value(s), so it is up to the script to decide. I personally love what we have now, just return values.
* Separate in different folders, one for timings, one for other values. Something like <code>metrics/timings</code> and <code>metrics/data</code> (don't love the name data) and generate *statistics.timings* *statistics.data*.  Then for the for user metrics *statistics.usermetrics* meaning users can't separate timings and other data, but I think that is ok?

**Comment by tobli** [comment]
Conclusions based on discussions offline - separate builtin metrics from data collected from user provided scripts (custom data). Furthermore separate dynamic data (collected for each run) from static data (collected once per page). The resulting structure would look like this (naming is not yet finalized):
```
{
… // basic metadata such as time, url, browsertime version
"builtin" : {
  "statistics" : [
    {…},
    …
  ],
  "data" : {
    "static" : {
      "documentTitle" : "My homepage",
      …
    },
    "dynamic" : {
      "speedIndex" : 478.22,
      …
    }
  },
"custom" : {
  "statistics" : [
    {…},
    …
  ],
  "data" : {
    "static" : {
      "numberOfLinks" : 42,
      …
    },
    "dynamic" : {
      "mySpeedMetric" : 17.094,
      …
    }
  }
}
```
Some data that is currently listed as top level entries, and specified in the Browsertime source code (such as browser name and version) will be moved into built-in static scripts. This makes the Browsertime core logic more generic, treating built-in and user provided scripts in a unified way. Separation of static and dynamic user provided scripts is not yet possibly, but will likely be based on folder names in the script folder provided via the --scriptPath argument.

**Comment by soulgalore** [comment]
ok, fixed a rough version in master, needs some cleanup, so lets go through it this weekend and cleanup the code and make see if we can find a better naming and if something is missing in the structure.

**Comment by soulgalore** [comment]
this is pretty clean now, just update the docs and it is finished.

**Comment by soulgalore** [comment]
fixed and released
