### ISSUE TITLE
npm install on windows broken

### ISSUE THREAD

**Issue by cbautista-dev** [tobli/browsertime#87]
Just wondering if this is an error in our network or is a  broken build. Please find screenshot below
I've done this 10 times in 3 different windows machines

![capture](https://cloud.githubusercontent.com/assets/11806420/8678634/709a6196-2a0a-11e5-9f87-a535149948d7.PNG)

**Comment by tobli** [comment]
Hi!
That's very strange, haven't seen any other report of this. I don't have a Windows system for testing - @soulgalore have you seen this? 63e8a0dc33b08f48c542a0ee44abde8063f94c86 is indeed the expected checksum for the 0.9.8 release. Not sure what could cause your downloaded tgz file to have a different checksum.

**Comment by soulgalore** [comment]
@tobli no but I'm not sure I've tested the latest version, will have a go later when I find the time.

**Comment by chrisbautista** [comment]
Hi! @tobli @soulgalore thanks looking forward to what you find out.  this happened while installing sitespeed.io and just browsertime.

**Comment by cbautista-dev** [comment]
Update:  I got a hold of a non-company windows machine(hooked to the guest wifi) and able to install with no problem. No problems with the checksums. It's either the network or the machine I use for work.  I try isolate.   

What puzzles me is I can install pretty much any npm module and have no issues but this module just fails.

**Comment by tobli** [comment]
Thanks for the update! Glad it worked out for you, but still strange. I'll close the issue for now, but please re-open or comment if you find any additional information.
