### ISSUE TITLE
Normalize Navigation Timing data

### ISSUE THREAD

**Issue by soulgalore** [tobli/browsertime#88]
In the output JSON we have the timestamp data for each and every metric. it would be smarter to have it normalized to navigation start, so the values is actually readable.

I'll fix this if I get an ok from @tobli :)

Then as an extra thing, we could add make a hack to put the navigation timings in the statistics.

**Comment by tobli** [comment]
:+1:

**Comment by soulgalore** [comment]
one thing: now I kept the structure plain in the stats, everything on one level, maybe we should keep Navigation Timings in an own subset so it's easy to spot?

**Comment by soulgalore** [comment]
I need to investigate if we should keep it on the same level or not. Will close when I checked it.

**Comment by soulgalore** [comment]
Then I guess it would be nice of a release to get out the new dependencies and we can do a release of sitespeed.io so we can push the metrics to the dashboard.

**Comment by soulgalore** [comment]
so right: I'm not 100% sure about the way forward.  Right now it looks like this:
<pre>
  "default": {
    "statistics": {
      "backEndTime": {
        "min": "511",
        "max": "511",
        "p10": "511",
        "p70": "511",
        "p80": "511",
        "p90": "511",
        "p99": "511",
        "median": "511",
        "mean": "511"
      }, 
 "connectStart": {
        "min": "217",
        "max": "217",
        "p10": "217",
        "p70": "217",
        "p80": "217",
        "p90": "217",
        "p99": "217",
        "median": "217",
        "mean": "217"
      }, ...

</pre>

So for someone to use it (sitespeed.io at least) we need to keep a list of all the names in the navigation timings, And that maybe is ok? The timings we fetch using the naming standard of ending with Time.

Else we could do something like
<pre>
"default": {
    "statistics": {
      "navigationTiming": {
      "connectStart": {
        "min": "217",
        "max": "217",
        "p10": "217",
        "p70": "217",
        "p80": "217",
        "p90": "217",
        "p99": "217",
        "median": "217",
        "mean": "217"
      }, ...
</pre>
but then we break the flatness. Lets have a talk to sync before we release (will need 2do some adjustments in sitespeed.io first,

**Comment by soulgalore** [comment]
lets keep it as is now and then do a refactoring for 1.0
