### ISSUE TITLE
Exception Error:  propertyname undefined

### ISSUE THREAD

**Issue by chrisbautista** [tobli/browsertime#93]
Hi Tobli

Great work! 

I am running browsertime 0.10.2 against a selenium grid. We can see a session start and I see files being created but then it times out and returns the errors below. 

Any ideas? is this a bug. I also see it showing in sitespeed when calling browsertime

Warm regards

Chris

```
Fetching http://N124F7LU4VMKXHN:3000 (1 of 1)
loading url took 23871 milliseconds
Storing C:\Users\43904801\Desktop\Projects\PresentationAug2015\SitespeedDemo\sitespeed-result\n124f7lu4vmkxhn\2015-08-27-10-50-52\data\har\chrome\n124f7lu4vmkxhn.har
Storing C:\Users\43904801\Desktop\Projects\PresentationAug2015\SitespeedDemo\sitespeed-result\n124f7lu4vmkxhn\2015-08-27-10-50-52\data\browsertime\chrome\n124f7lu4vmkxhn-brow
rtime.json
Catched an uncaught exception:TypeError: Cannot set property 'name' of undefinedTypeError: Cannot set property 'name' of undefined
    at C:\swdtools\nodejs\node_modules\sitespeed.io\node_modules\browsertime\lib\proxy\mobproxy.js:224:29
    at IncomingMessage.<anonymous> (C:\swdtools\nodejs\node_modules\sitespeed.io\node_modules\browsertime\node_modules\browsermob-proxy-api\index.js:186:46)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
Stopping proxy

```

**Comment by soulgalore** [comment]
Hi @chrisbautista 
ok, so I think this is the problem: If you run is with default setting, it will use browsermobproxy (the proxy we use to collect HAR data), it runs locally where you start the script but you do the test with the grid. So you need to run without the proxy (meaning you will get no HAR) but you will get all the timings from the browser. You can turn it off with <code>--useProxy false</code>
Hope that helps!
Best
Peter

**Comment by soulgalore** [comment]
To get it to work in sitespeed.io this issue needs to be fixed: https://github.com/sitespeedio/sitespeed.io/issues/735

**Comment by chrisbautista** [comment]
@soulgalore 

Thanks for looking into this. I will try your suggestion when I get a chance. I thought that using seleniumServer parameter would disable browsermobproxy. Would installing browsermobproxy on the selenium hub and nodes fix this?

Once again awesome job guys! :)

Warm regards
Chris

**Comment by tobli** [comment]
Hi!
Sorry for the huge delay in answering. I'm going to close this issue now. Please feel free to open new issues if there are issues that still persists. Note however that the 0.x code base (current master) has a number of issues with stability in certain situations. The 1.0 branch is an ongoing rewrite, based on newer node, Selenium and using a Promise-based architecture for managing asynchronous tasks. We hope to have in ready in a few months.

All the best
/Tobias

**Comment by parangsjo** [comment]
Hi,

There are a couple of books that inspire me to do really great things, here is the list of that books <http://stytutroxo.bestplanbforu.org/xyntpbq>

pa@rangsjo.com
