### ISSUE TITLE
New Feature: request blocking

### ISSUE THREAD

**Issue by okor** [tobli/browsertime#98]
It is sometimes helpful / required to block requests from a domain or by regex - for various automation tasks. It would be helpful here. I suggest adding the ability to block requests by regex.

**Comment by tobli** [comment]
Hi,
BrowserMobProxy has a feature to return a specific http status code (such as 404 or 500) for requests matching a regex, is that the kind of blocking you'd need?

**Comment by okor** [comment]
Yes, exactly. The goal here would be to replicate some sort of ad blocking functionality.

**Comment by tobli** [comment]
Would you be able to try from this branch?
https://github.com/tobli/browsertime/tree/blacklist-urls

**Comment by okor** [comment]
@tobli That branch seems to work perfectly. I only tested the blacklist regex and confirmed it actually blocked what it should. It did. Didn't mess with the status and method options. Looks great. 

Thank you!

**Comment by okor** [comment]
@tobli It's not total blocker - but it would be cool to see this change go out in a new published release.

If you are curious, I'm using browsertime for this: https://github.com/voxmedia/lightbike and our devs will be using this tool very soon to perform regular and simple asset budget audits while developing Vox Media things - as one slice of our much larger performance pie.

**Comment by tobli** [comment]
Hi @okor 
Sorry for the delay. I'll make a release with this included today.

Great to see your use of it. I'm hoping the 1.0 rewrite I'm working on (in a branch) will work even better for you. It doesn't have all the features of the current version yet, but it's proven to be much more stable in the testing I've done. Neither the cli nor the api will be identical, but the changes should be for the better, and I hope the transition should be easy. Hoping to get something out in a few weeks.

/Tobias

**Comment by okor** [comment]
@tobli That's awesome! Thank you : )

I haven't had many issues other than PhantomJS being very slow and not exiting in a predictable manor. I am just pointing a browser at a webpage and generating a HAR (doesn't require window.performance API since you have a slick proxy for capturing network request - nice solve). It would be very nice to be able to use PhantomJS for this task as it could theoretically be a lighter weight tool (which devs would appreciate) and a biggy - no need to have a Chrome window open on the desktop. I'm looking into creating a virtual Xsession for OSx so I can tell Chrome to render there rather than on a real display. Not sure what the better option is.

Thanks for your work, the tool is very helpful as is : )

**Comment by cgoldberg** [comment]
> I'm looking into creating a virtual Xsession for OSx
> so I can tell Chrome to render there rather than on a real display.

@okor,

It's pretty trivial to launch your browser inside a virtual display... you can even run it on a server with no physical display attached.  I prefer driving a real browser that is hidden rather than something headless like PhantomJS.

The solution on Linux is to use Xvfb (X Virtual Framebuffer)... it's available with X11 and is launched using `xvfb-run`.  I believe a similar virtual display exists as part of Xquartz for Mac (i've never used it).

hth,
-Corey

**Comment by cgoldberg** [comment]
related to request blocking: https://engineering.groupon.com/2013/misc/black-hole-proxy-for-selenium-testing/
(take note of the 3rd comment)

**Comment by okor** [comment]
@cgoldberg Yeah, that's exactly what I was looking into - Xquartz. Glad to hear it's trivial ... I hope that holds up haha. Will be the next "big" feature for the auditing tool.

**Comment by okor** [comment]
@tobli is there an option for where to dump the browsermobproxy.log and browsertime.log files? For the tool I'm building it would be ideal to control that.

**Comment by tobli** [comment]
@okor yes, try --logDir

**Comment by tobli** [comment]
@okor version 0.12.2 is out now. Forgot to credit you in the changelog… sorry about that.

**Comment by okor** [comment]
@tobli Thanks again!
